# Application constants

DEFAULT_ID_COLUMN <- 'USUBJID'
DEFAULT_VISIT_COLUMN <- 'AVISIT'
DEFAULT_VISITN_COLUMN <- 'AVISITN'
DEFAULT_VALUE_COLUMN <- 'AVAL'
DEFAULT_PARAMETER_COLUMN <- 'PARAM'
DEFAULT_TRT_COLUMN <- 'TRTA'
